version: '3.9'
services:
  kong-db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: ${KONG_DB_USERNAME}
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD}
      POSTGRES_DB: ${KONG_DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_DB_USERNAME}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    container_name: "kong-db"
    tty: true
    networks:
      - kong-net

  kong-migrations:
    image: kong:latest
    entrypoint: sh -c "sleep 10 && kong migrations bootstrap -v"
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_DB_HOST}
      KONG_PG_DATABASE: ${KONG_DB_NAME}
      KONG_PG_USER: ${KONG_DB_USERNAME}
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
    container_name: "kong-migration"
    depends_on:
      - kong-db
    networks:
      - kong-net
    restart: on-failure

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_DB_HOST}
      KONG_PG_DATABASE: ${KONG_DB_NAME}
      KONG_PG_USER: ${KONG_DB_USERNAME}
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
      KONG_PROXY_ACCESS_LOG: ${KONG_PROXY_ACCESS_LOG}
      KONG_ADMIN_ACCESS_LOG: ${KONG_ADMIN_ACCESS_LOG}
      KONG_PROXY_ERROR_LOG: ${KONG_PROXY_ERROR_LOG}
      KONG_ADMIN_ERROR_LOG: ${KONG_ADMIN_ERROR_LOG}
      KONG_ADMIN_LISTEN: ${KONG_ADMIN_LISTEN}
    restart: on-failure
    container_name: "kong"
    ports:
      - $KONG_PROXY_PORT:8000
      - $KONG_PROXY_SSL_PORT:8443
      - $KONG_PROXY_ADMIN_API_PORT:8001
      - $KONG_PROXY_ADMIN_SSL_API_PORT:8444
    networks:
      - kong-net

  konga-db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: ${KONGA_DB_USERNAME}
      POSTGRES_PASSWORD: ${KONGA_DB_PASSWORD}
      POSTGRES_DB: ${KONG_DB_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${KONGA_DB_USERNAME}" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    container_name: "konga-db"
    tty: true
    networks:
      - kong-net

  konga:
    image: pantsel/konga
    environment:
      TOKEN_SECRET: ${KONGA_TOKEN_SECRET}
      DB_ADAPTER: ${KONG_DATABASE}
      DB_HOST: ${KONGA_DB_HOST}
      DB_PORT: ${KONGA_DB_PORT}
      DB_DATABASE: ${KONGA_DB_NAME}
      DB_USER: ${KONGA_DB_USERNAME}
      DB_PASSWORD: ${KONGA_DB_PASSWORD}
      NODE_ENV: ${KONGA_ENV}
      KONGA_HOOK_TIMEOUT: 120000
    restart: on-failure
    container_name: "konga"
    ports:
      - $KONGA_PORT:1337
    depends_on:
      - konga-db
    networks:
      - kong-net

volumes:
  persist_volume:

networks:
  kong-net:
    external: true